version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: paymentservice-db
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    volumes:
      - paymentservice_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5

  migrations:
    build: .
    container_name: paymentservice-migrations
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: alembic upgrade head
    volumes:
      - .:/app

  web:
    build: .
    container_name: paymentservice-web
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: "1"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  paymentservice_db_data:
