version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: paymentservice-db
    ports:
      - "5433:5432"  # Evita conflito com outro serviço
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - paymentservice_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks: [fastfood]

  migrations:
    build: .
    container_name: paymentservice-migrations
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: alembic upgrade head
    volumes:
      - .:/app
    networks: [fastfood]

  web:
    build: .
    container_name: paymentservice-web
    ports:
      - "8002:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    networks: [fastfood]

volumes:
  paymentservice_db_data:

networks:
  fastfood:
    external: true
    name: fastfood-service
