name: PR Terraform Plan

on:
  pull_request:
    branches: [ main, master ]

jobs:
  validate_terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_db_host     : ${{ secrets.DB_HOST }}
          TF_VAR_db_port     : ${{ secrets.DB_PORT }}
          TF_VAR_db_user     : ${{ secrets.DB_USER }}
          TF_VAR_db_password : ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name     : ${{ secrets.DB_NAME }}
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true
